CREATE TABLE IF NOT EXISTS ACT_RE_DEPLOYMENT (
  ID_          VARCHAR(64)  NOT NULL,
  NAME_        INT(11) DEFAULT NULL,
  CATEGORY_    VARCHAR(255) DEFAULT NULL,
  TENANT_ID_   VARCHAR(255) DEFAULT '',
  DEPLOY_TIME_ VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID_)
);
