CREATE TABLE sessions(
  id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  session_id VARCHAR(255) NOT NULL,
  data VARCHAR(2000) ,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = MEMORY;

-- //@UNDO

DROP TABLE sessions;
