
CREATE TABLE msp_incidents (
  id int(10) unsigned NOT NULL AUTO_INCREMENT,
  number varchar(32) NOT NULL ,
  requester_name varchar(255) ,
  requester_location varchar(255) DEFAULT NULL ,
  requester_email varchar(255) DEFAULT NULL ,
  requester_phone varchar(255) DEFAULT NULL ,
  request_type varchar(255) DEFAULT NULL ,
  request_description varchar(255) NOT NULL ,
  service_catalog varchar(255) DEFAULT NULL ,
  category varchar(45) DEFAULT NULL ,
  impact varchar(255) DEFAULT NULL ,
  urgency varchar(255) DEFAULT NULL ,
  priority varchar(255) DEFAULT NULL ,
  ci_type varchar(255) DEFAULT NULL ,
  ci varchar(255) DEFAULT NULL ,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  created_by varchar(255) DEFAULT NULL  ,
  updated_by varchar(255) DEFAULT NULL ,
  assigned_user varchar(255) DEFAULT NULL ,
  assigned_group varchar(255) DEFAULT NULL ,
  response_time timestamp NULL DEFAULT NULL ,
  resolve_time timestamp NULL DEFAULT NULL ,
  close_time timestamp NULL DEFAULT NULL ,
  solution varchar(2000) DEFAULT NULL ,
  close_code varchar(255) DEFAULT NULL ,
  can_process tinyint(1) DEFAULT NULL ,
  resolved tinyint(1) DEFAULT NULL ,
  hardware_error tinyint(1) DEFAULT NULL ,
  msu_account_name varchar(255) DEFAULT NULL ,
  msp_account_name varchar(255) DEFAULT NULL ,
  msu_instance_id varchar(255) ,
  msp_instance_id varchar(255) DEFAULT NULL ,
  msu_status varchar(255) DEFAULT NULL ,
  msp_status varchar(255) DEFAULT NULL ,
  PRIMARY KEY (id),
  UNIQUE KEY number_UNIQUE (number)
);


