CREATE TABLE sessions(
  id INT(4) NOT NULL,
  session_id VARCHAR(25) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  data TEXT(16) ,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
)ENGINE = MEMORY;

-- //@UNDO

DROP TABLE sessions;
