CREATE TABLE sessions(
ID NUMERIC(20,0) NOT NULL,
APPLIED_AT VARCHAR(25) NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL
);

ALTER TABLE sessions
ADD CONSTRAINT PK_sessions
PRIMARY KEY (id);

-- //@UNDO

DROP TABLE sessions;
