CREATE TABLE users (
ID NUMERIC(20,0) NOT NULL,
APPLIED_AT VARCHAR(25) NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL
);

ALTER TABLE users
ADD CONSTRAINT PK_users
PRIMARY KEY (id);

-- //@UNDO

DROP TABLE users;
