CREATE TABLE users (
  id NUMERIC(20,0) NOT NULL,
  name VARCHAR(25) NOT NULL,
  password VARCHAR(255) NOT NULL
);

ALTER TABLE users
ADD CONSTRAINT PK_users
PRIMARY KEY (id);

-- //@UNDO

DROP TABLE users;
